// Generated by CoffeeScript 1.9.2
var TestTransform, fs, inStream;

fs = require('fs');

TestTransform = require('./test-transform');

inStream = new TestTransform;

fs.createReadStream("./test.coffee").pipe(inStream);

inStream.on('data', function(chunk) {
  var f, line;
  line = chunk.toString();
  process.stdout.write("-->" + line);
  if (line.match(/line\.match/g)) {
    inStream.pause();
    f = fs.createReadStream("./test.coffee");
    f.on('end', function() {
      return inStream.resume();
    });
    return f.pipe(process.stdout);
  }
});
